// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/debondingdelegation/debondingdelegationpb/debonding_delegation.proto

package debondingdelegationpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DebondingDelegationEntry struct {
	Entries              map[string]*DebondingDelegationInnerEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *DebondingDelegationEntry) Reset()         { *m = DebondingDelegationEntry{} }
func (m *DebondingDelegationEntry) String() string { return proto.CompactTextString(m) }
func (*DebondingDelegationEntry) ProtoMessage()    {}
func (*DebondingDelegationEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba916d0766223a0e, []int{0}
}

func (m *DebondingDelegationEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebondingDelegationEntry.Unmarshal(m, b)
}
func (m *DebondingDelegationEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebondingDelegationEntry.Marshal(b, m, deterministic)
}
func (m *DebondingDelegationEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebondingDelegationEntry.Merge(m, src)
}
func (m *DebondingDelegationEntry) XXX_Size() int {
	return xxx_messageInfo_DebondingDelegationEntry.Size(m)
}
func (m *DebondingDelegationEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DebondingDelegationEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DebondingDelegationEntry proto.InternalMessageInfo

func (m *DebondingDelegationEntry) GetEntries() map[string]*DebondingDelegationInnerEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type DebondingDelegationInnerEntry struct {
	DebondingDelegations []*DebondingDelegation `protobuf:"bytes,1,rep,name=debondingDelegations,proto3" json:"debondingDelegations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DebondingDelegationInnerEntry) Reset()         { *m = DebondingDelegationInnerEntry{} }
func (m *DebondingDelegationInnerEntry) String() string { return proto.CompactTextString(m) }
func (*DebondingDelegationInnerEntry) ProtoMessage()    {}
func (*DebondingDelegationInnerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba916d0766223a0e, []int{1}
}

func (m *DebondingDelegationInnerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebondingDelegationInnerEntry.Unmarshal(m, b)
}
func (m *DebondingDelegationInnerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebondingDelegationInnerEntry.Marshal(b, m, deterministic)
}
func (m *DebondingDelegationInnerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebondingDelegationInnerEntry.Merge(m, src)
}
func (m *DebondingDelegationInnerEntry) XXX_Size() int {
	return xxx_messageInfo_DebondingDelegationInnerEntry.Size(m)
}
func (m *DebondingDelegationInnerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DebondingDelegationInnerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DebondingDelegationInnerEntry proto.InternalMessageInfo

func (m *DebondingDelegationInnerEntry) GetDebondingDelegations() []*DebondingDelegation {
	if m != nil {
		return m.DebondingDelegations
	}
	return nil
}

type DebondingDelegation struct {
	Shares               []byte   `protobuf:"bytes,1,opt,name=shares,proto3" json:"shares,omitempty"`
	DebondEndTime        uint64   `protobuf:"varint,2,opt,name=DebondEndTime,proto3" json:"DebondEndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebondingDelegation) Reset()         { *m = DebondingDelegation{} }
func (m *DebondingDelegation) String() string { return proto.CompactTextString(m) }
func (*DebondingDelegation) ProtoMessage()    {}
func (*DebondingDelegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba916d0766223a0e, []int{2}
}

func (m *DebondingDelegation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebondingDelegation.Unmarshal(m, b)
}
func (m *DebondingDelegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebondingDelegation.Marshal(b, m, deterministic)
}
func (m *DebondingDelegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebondingDelegation.Merge(m, src)
}
func (m *DebondingDelegation) XXX_Size() int {
	return xxx_messageInfo_DebondingDelegation.Size(m)
}
func (m *DebondingDelegation) XXX_DiscardUnknown() {
	xxx_messageInfo_DebondingDelegation.DiscardUnknown(m)
}

var xxx_messageInfo_DebondingDelegation proto.InternalMessageInfo

func (m *DebondingDelegation) GetShares() []byte {
	if m != nil {
		return m.Shares
	}
	return nil
}

func (m *DebondingDelegation) GetDebondEndTime() uint64 {
	if m != nil {
		return m.DebondEndTime
	}
	return 0
}

type GetByAddressRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByAddressRequest) Reset()         { *m = GetByAddressRequest{} }
func (m *GetByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetByAddressRequest) ProtoMessage()    {}
func (*GetByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba916d0766223a0e, []int{3}
}

func (m *GetByAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByAddressRequest.Unmarshal(m, b)
}
func (m *GetByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByAddressRequest.Merge(m, src)
}
func (m *GetByAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetByAddressRequest.Size(m)
}
func (m *GetByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByAddressRequest proto.InternalMessageInfo

func (m *GetByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetByAddressRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByAddressResponse struct {
	DebondingDelegations map[string]*DebondingDelegationInnerEntry `protobuf:"bytes,1,rep,name=debonding_delegations,json=debondingDelegations,proto3" json:"debonding_delegations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *GetByAddressResponse) Reset()         { *m = GetByAddressResponse{} }
func (m *GetByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetByAddressResponse) ProtoMessage()    {}
func (*GetByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba916d0766223a0e, []int{4}
}

func (m *GetByAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByAddressResponse.Unmarshal(m, b)
}
func (m *GetByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByAddressResponse.Merge(m, src)
}
func (m *GetByAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetByAddressResponse.Size(m)
}
func (m *GetByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByAddressResponse proto.InternalMessageInfo

func (m *GetByAddressResponse) GetDebondingDelegations() map[string]*DebondingDelegationInnerEntry {
	if m != nil {
		return m.DebondingDelegations
	}
	return nil
}

func init() {
	proto.RegisterType((*DebondingDelegationEntry)(nil), "debondingdelegation.DebondingDelegationEntry")
	proto.RegisterMapType((map[string]*DebondingDelegationInnerEntry)(nil), "debondingdelegation.DebondingDelegationEntry.EntriesEntry")
	proto.RegisterType((*DebondingDelegationInnerEntry)(nil), "debondingdelegation.DebondingDelegationInnerEntry")
	proto.RegisterType((*DebondingDelegation)(nil), "debondingdelegation.DebondingDelegation")
	proto.RegisterType((*GetByAddressRequest)(nil), "debondingdelegation.GetByAddressRequest")
	proto.RegisterType((*GetByAddressResponse)(nil), "debondingdelegation.GetByAddressResponse")
	proto.RegisterMapType((map[string]*DebondingDelegationInnerEntry)(nil), "debondingdelegation.GetByAddressResponse.DebondingDelegationsEntry")
}

func init() {
	proto.RegisterFile("grpc/debondingdelegation/debondingdelegationpb/debonding_delegation.proto", fileDescriptor_ba916d0766223a0e)
}

var fileDescriptor_ba916d0766223a0e = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x9d, 0x56, 0x77, 0xf1, 0x6d, 0x05, 0x99, 0xae, 0x12, 0x03, 0x42, 0x09, 0x1e, 0xe2,
	0xa1, 0x09, 0xc4, 0x8b, 0xec, 0xcd, 0x75, 0xcb, 0xba, 0xd7, 0x6c, 0x4f, 0xa5, 0x20, 0xf9, 0xf1,
	0x4c, 0x86, 0xb6, 0x33, 0x71, 0x66, 0x5a, 0x1b, 0xc4, 0x93, 0x67, 0xff, 0x47, 0xff, 0x14, 0x69,
	0x7e, 0xd8, 0x16, 0xa7, 0x12, 0x0f, 0xde, 0xf2, 0xbe, 0xf9, 0xbe, 0xef, 0x63, 0x3e, 0xf3, 0x18,
	0xb8, 0xcb, 0x64, 0x91, 0xf8, 0x29, 0xc6, 0x82, 0xa7, 0x8c, 0x67, 0x29, 0x2e, 0x31, 0x8b, 0x34,
	0x13, 0xdc, 0xa4, 0x15, 0xf1, 0x5e, 0xfd, 0xb8, 0x97, 0xbd, 0x42, 0x0a, 0x2d, 0xe8, 0xd0, 0xd0,
	0xe1, 0xfc, 0x24, 0x60, 0xdd, 0xb4, 0xfa, 0xcd, 0x6f, 0x7d, 0xc2, 0xb5, 0x2c, 0xe9, 0x14, 0xce,
	0x91, 0x6b, 0xc9, 0x50, 0x59, 0x64, 0xd4, 0x77, 0x2f, 0x82, 0x2b, 0xcf, 0x90, 0xe1, 0x9d, 0xea,
	0xf7, 0x26, 0x75, 0x73, 0x55, 0x84, 0x6d, 0x94, 0xcd, 0x61, 0x70, 0xf8, 0x83, 0x3e, 0x85, 0xfe,
	0x02, 0x4b, 0x8b, 0x8c, 0x88, 0xfb, 0x38, 0xdc, 0x7d, 0xd2, 0x0f, 0xf0, 0x68, 0x13, 0x2d, 0xd7,
	0x68, 0xf5, 0x46, 0xc4, 0xbd, 0x08, 0x82, 0xae, 0x53, 0xef, 0x38, 0x47, 0x59, 0x4f, 0xab, 0x03,
	0xae, 0x7a, 0x6f, 0x89, 0xf3, 0x0d, 0x5e, 0xfe, 0xd5, 0x4b, 0xe7, 0x70, 0x99, 0xfe, 0x69, 0x68,
	0xcf, 0xec, 0x76, 0x9d, 0x1e, 0x1a, 0x53, 0x9c, 0x7b, 0x18, 0x1a, 0xcc, 0xf4, 0x39, 0x9c, 0xa9,
	0x3c, 0x92, 0x15, 0x5a, 0xe2, 0x0e, 0xc2, 0xa6, 0xa2, 0xaf, 0xe0, 0x49, 0x6d, 0x9f, 0xf0, 0x74,
	0xca, 0x56, 0x35, 0x83, 0x87, 0xe1, 0xb1, 0xe8, 0xdc, 0xc2, 0xf0, 0x16, 0xf5, 0x75, 0xf9, 0x2e,
	0x4d, 0x25, 0x2a, 0x15, 0xe2, 0xe7, 0x35, 0x2a, 0x4d, 0x2d, 0x38, 0x8f, 0x6a, 0xa5, 0xc1, 0xd9,
	0x96, 0xbb, 0x71, 0x39, 0xb2, 0x2c, 0xd7, 0x55, 0x5e, 0x3f, 0x6c, 0x2a, 0xe7, 0x47, 0x0f, 0x2e,
	0x8f, 0x93, 0x54, 0x21, 0xb8, 0x42, 0xba, 0x85, 0x67, 0xa6, 0x5d, 0x6a, 0xa9, 0xbc, 0x37, 0x52,
	0x31, 0x25, 0x99, 0x50, 0x35, 0x2b, 0x61, 0x04, 0x66, 0x7f, 0x85, 0x17, 0x27, 0x5b, 0xfe, 0xf7,
	0xb2, 0x04, 0xdf, 0x09, 0xd8, 0x06, 0xf3, 0x3d, 0xca, 0x0d, 0x4b, 0x90, 0x22, 0x0c, 0x0e, 0xcf,
	0x48, 0xdd, 0x0e, 0x18, 0xaa, 0xab, 0xb1, 0x5f, 0x77, 0x06, 0xe6, 0x3c, 0xb8, 0x9e, 0xcf, 0x66,
	0x19, 0xd3, 0xf9, 0x3a, 0xf6, 0x12, 0xb1, 0xf2, 0x3f, 0xb1, 0x6c, 0x85, 0x5c, 0x8f, 0x39, 0xea,
	0x2f, 0x42, 0x2e, 0x94, 0x2f, 0x22, 0xc5, 0xd4, 0x58, 0x16, 0xc9, 0xb8, 0x90, 0x62, 0x5b, 0xfa,
	0xff, 0xf6, 0x46, 0xc4, 0x67, 0xd5, 0x7b, 0xf0, 0xe6, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e,
	0xf9, 0x2a, 0x1e, 0x5c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DebondingDelegationServiceClient is the client API for DebondingDelegationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DebondingDelegationServiceClient interface {
	GetByAddress(ctx context.Context, in *GetByAddressRequest, opts ...grpc.CallOption) (*GetByAddressResponse, error)
}

type debondingDelegationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDebondingDelegationServiceClient(cc grpc.ClientConnInterface) DebondingDelegationServiceClient {
	return &debondingDelegationServiceClient{cc}
}

func (c *debondingDelegationServiceClient) GetByAddress(ctx context.Context, in *GetByAddressRequest, opts ...grpc.CallOption) (*GetByAddressResponse, error) {
	out := new(GetByAddressResponse)
	err := c.cc.Invoke(ctx, "/debondingdelegation.DebondingDelegationService/GetByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebondingDelegationServiceServer is the server API for DebondingDelegationService service.
type DebondingDelegationServiceServer interface {
	GetByAddress(context.Context, *GetByAddressRequest) (*GetByAddressResponse, error)
}

// UnimplementedDebondingDelegationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDebondingDelegationServiceServer struct {
}

func (*UnimplementedDebondingDelegationServiceServer) GetByAddress(ctx context.Context, req *GetByAddressRequest) (*GetByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByAddress not implemented")
}

func RegisterDebondingDelegationServiceServer(s *grpc.Server, srv DebondingDelegationServiceServer) {
	s.RegisterService(&_DebondingDelegationService_serviceDesc, srv)
}

func _DebondingDelegationService_GetByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebondingDelegationServiceServer).GetByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/debondingdelegation.DebondingDelegationService/GetByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebondingDelegationServiceServer).GetByAddress(ctx, req.(*GetByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DebondingDelegationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "debondingdelegation.DebondingDelegationService",
	HandlerType: (*DebondingDelegationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByAddress",
			Handler:    _DebondingDelegationService_GetByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/debondingdelegation/debondingdelegationpb/debonding_delegation.proto",
}
