// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction/transactionpb/transaction.proto

package transactionpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SignatureVerified    bool     `protobuf:"varint,2,opt,name=signature_verified,json=signatureVerified,proto3" json:"signature_verified,omitempty"`
	SanityChecked        bool     `protobuf:"varint,3,opt,name=sanity_checked,json=sanityChecked,proto3" json:"sanity_checked,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	PublicKey            string   `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature            string   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce                uint64   `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Fee                  []byte   `protobuf:"bytes,8,opt,name=fee,proto3" json:"fee,omitempty"`
	GasLimit             uint64   `protobuf:"varint,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,10,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Method               string   `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c97cb22cbc6386c, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Transaction) GetSignatureVerified() bool {
	if m != nil {
		return m.SignatureVerified
	}
	return false
}

func (m *Transaction) GetSanityChecked() bool {
	if m != nil {
		return m.SanityChecked
	}
	return false
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Transaction) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetFee() []byte {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *Transaction) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *Transaction) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type GetByHeightRequest struct {
	Height               int64    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByHeightRequest) Reset()         { *m = GetByHeightRequest{} }
func (m *GetByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetByHeightRequest) ProtoMessage()    {}
func (*GetByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c97cb22cbc6386c, []int{1}
}

func (m *GetByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightRequest.Unmarshal(m, b)
}
func (m *GetByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightRequest.Merge(m, src)
}
func (m *GetByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetByHeightRequest.Size(m)
}
func (m *GetByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightRequest proto.InternalMessageInfo

func (m *GetByHeightRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByHeightResponse struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetByHeightResponse) Reset()         { *m = GetByHeightResponse{} }
func (m *GetByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetByHeightResponse) ProtoMessage()    {}
func (*GetByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c97cb22cbc6386c, []int{2}
}

func (m *GetByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByHeightResponse.Unmarshal(m, b)
}
func (m *GetByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByHeightResponse.Merge(m, src)
}
func (m *GetByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetByHeightResponse.Size(m)
}
func (m *GetByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByHeightResponse proto.InternalMessageInfo

func (m *GetByHeightResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*GetByHeightRequest)(nil), "transaction.GetByHeightRequest")
	proto.RegisterType((*GetByHeightResponse)(nil), "transaction.GetByHeightResponse")
}

func init() {
	proto.RegisterFile("transaction/transactionpb/transaction.proto", fileDescriptor_7c97cb22cbc6386c)
}

var fileDescriptor_7c97cb22cbc6386c = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdb, 0xab, 0xd3, 0x40,
	0x10, 0xc6, 0x4d, 0xd3, 0x5b, 0x26, 0xad, 0x97, 0x51, 0x64, 0xf1, 0x82, 0x21, 0x20, 0x04, 0xd4,
	0x0a, 0xf5, 0xd5, 0xa7, 0xfa, 0xa0, 0xa0, 0x0f, 0xb2, 0x15, 0x1f, 0x7c, 0x09, 0xe9, 0x76, 0x9a,
	0x2c, 0x6d, 0x93, 0x98, 0xdd, 0x14, 0xf2, 0x1f, 0x9e, 0x3f, 0xeb, 0x90, 0x4d, 0xdb, 0xb3, 0xe1,
	0x70, 0xde, 0xe6, 0xf7, 0x7d, 0x5f, 0x32, 0xc3, 0xce, 0xc0, 0x07, 0x5d, 0x25, 0xb9, 0x4a, 0x84,
	0x96, 0x45, 0xfe, 0xd9, 0xaa, 0xcb, 0x8d, 0x4d, 0x8b, 0xb2, 0x2a, 0x74, 0x81, 0xbe, 0x25, 0x85,
	0x37, 0x03, 0xf0, 0xff, 0xdc, 0x31, 0x32, 0x98, 0xa8, 0x5a, 0x08, 0x52, 0x8a, 0x39, 0x81, 0x13,
	0x4d, 0xf9, 0x05, 0xf1, 0x13, 0xa0, 0x92, 0x69, 0x9e, 0xe8, 0xba, 0xa2, 0xf8, 0x44, 0x95, 0xdc,
	0x49, 0xda, 0xb2, 0x81, 0x09, 0x3d, 0xbb, 0x3a, 0x7f, 0xcf, 0x06, 0xbe, 0x87, 0xc7, 0x2a, 0xc9,
	0xa5, 0x6e, 0x62, 0x91, 0x91, 0xd8, 0xd3, 0x96, 0xb9, 0x26, 0x3a, 0xef, 0xd4, 0x6f, 0x9d, 0x88,
	0x08, 0xc3, 0x2c, 0x51, 0x19, 0x1b, 0x06, 0x4e, 0xe4, 0x71, 0x53, 0xe3, 0x5b, 0x80, 0xb2, 0xde,
	0x1c, 0xa4, 0x88, 0xf7, 0xd4, 0xb0, 0x91, 0x71, 0xbc, 0x4e, 0xf9, 0x49, 0x0d, 0xbe, 0x01, 0xef,
	0xda, 0x8e, 0x8d, 0x3b, 0xf7, 0x2a, 0xe0, 0x0b, 0x18, 0xe5, 0x45, 0x2e, 0x88, 0x4d, 0x02, 0x27,
	0x1a, 0xf2, 0x0e, 0xf0, 0x29, 0xb8, 0x3b, 0x22, 0x36, 0x0d, 0x9c, 0x68, 0xc6, 0xdb, 0x12, 0x5f,
	0x83, 0x97, 0x26, 0x2a, 0x3e, 0xc8, 0xa3, 0xd4, 0xcc, 0x33, 0xd9, 0x69, 0x9a, 0xa8, 0x5f, 0x2d,
	0x5f, 0xcc, 0xb2, 0x92, 0x82, 0x18, 0x98, 0x8f, 0x5a, 0xf3, 0x77, 0xcb, 0xf8, 0x12, 0xc6, 0x47,
	0xd2, 0x59, 0xb1, 0x65, 0xbe, 0x69, 0x7e, 0xa6, 0xf0, 0x23, 0xe0, 0x77, 0xd2, 0xab, 0xe6, 0x07,
	0xc9, 0x34, 0xd3, 0x9c, 0xfe, 0xd7, 0xa4, 0x74, 0x9b, 0xce, 0x8c, 0x60, 0xde, 0xd3, 0xe5, 0x67,
	0x0a, 0xd7, 0xf0, 0xbc, 0x97, 0x56, 0x65, 0x91, 0x2b, 0xc2, 0xaf, 0x30, 0xb3, 0xd6, 0xd3, 0x2e,
	0xc1, 0x8d, 0xfc, 0x25, 0x5b, 0xd8, 0x6b, 0xb4, 0xf6, 0xc5, 0x7b, 0xe9, 0x65, 0x06, 0x68, 0x99,
	0x6b, 0xaa, 0x4e, 0xed, 0xc0, 0x1c, 0x7c, 0xab, 0x15, 0xbe, 0xeb, 0xfd, 0xec, 0xfe, 0xc8, 0xaf,
	0x82, 0x87, 0x03, 0xdd, 0x94, 0xe1, 0xa3, 0xd5, 0x93, 0x7f, 0xf3, 0xde, 0x9d, 0x6d, 0xc6, 0xe6,
	0xb8, 0xbe, 0xdc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x25, 0xa6, 0x2e, 0xb0, 0x8b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) GetByHeight(ctx context.Context, in *GetByHeightRequest, opts ...grpc.CallOption) (*GetByHeightResponse, error) {
	out := new(GetByHeightResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/GetByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	GetByHeight(context.Context, *GetByHeightRequest) (*GetByHeightResponse, error)
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) GetByHeight(ctx context.Context, req *GetByHeightRequest) (*GetByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByHeight not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_GetByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/GetByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetByHeight(ctx, req.(*GetByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByHeight",
			Handler:    _TransactionService_GetByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transactionpb/transaction.proto",
}
