// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/chain/chainpb/chain.proto

package chainpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Chain struct {
	Id                   string               `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	GenesisTime          *timestamp.Timestamp `protobuf:"bytes,3,opt,name=GenesisTime,proto3" json:"GenesisTime,omitempty"`
	Height               int64                `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{0}
}

func (m *Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain.Unmarshal(m, b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return xxx_messageInfo_Chain.Size(m)
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Chain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chain) GetGenesisTime() *timestamp.Timestamp {
	if m != nil {
		return m.GenesisTime
	}
	return nil
}

func (m *Chain) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetCurrentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentRequest) Reset()         { *m = GetCurrentRequest{} }
func (m *GetCurrentRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrentRequest) ProtoMessage()    {}
func (*GetCurrentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{1}
}

func (m *GetCurrentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentRequest.Unmarshal(m, b)
}
func (m *GetCurrentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentRequest.Merge(m, src)
}
func (m *GetCurrentRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrentRequest.Size(m)
}
func (m *GetCurrentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentRequest proto.InternalMessageInfo

type GetCurrentResponse struct {
	Chain                *Chain   `protobuf:"bytes,1,opt,name=Chain,proto3" json:"Chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentResponse) Reset()         { *m = GetCurrentResponse{} }
func (m *GetCurrentResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentResponse) ProtoMessage()    {}
func (*GetCurrentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce694d07bea9bb01, []int{2}
}

func (m *GetCurrentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentResponse.Unmarshal(m, b)
}
func (m *GetCurrentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentResponse.Merge(m, src)
}
func (m *GetCurrentResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentResponse.Size(m)
}
func (m *GetCurrentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentResponse proto.InternalMessageInfo

func (m *GetCurrentResponse) GetChain() *Chain {
	if m != nil {
		return m.Chain
	}
	return nil
}

func init() {
	proto.RegisterType((*Chain)(nil), "chain.Chain")
	proto.RegisterType((*GetCurrentRequest)(nil), "chain.GetCurrentRequest")
	proto.RegisterType((*GetCurrentResponse)(nil), "chain.GetCurrentResponse")
}

func init() { proto.RegisterFile("grpc/chain/chainpb/chain.proto", fileDescriptor_ce694d07bea9bb01) }

var fileDescriptor_ce694d07bea9bb01 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xbb, 0x4f, 0xc3, 0x30,
	0x10, 0xc6, 0x49, 0x5f, 0x12, 0x6e, 0x85, 0x84, 0x91, 0x50, 0xe8, 0x00, 0x55, 0xa6, 0x2e, 0xb1,
	0xa5, 0xb0, 0x30, 0x20, 0x84, 0xc8, 0x50, 0xba, 0x30, 0xa4, 0x9d, 0xd8, 0x92, 0xf4, 0xea, 0x58,
	0xe0, 0x07, 0xb6, 0xc3, 0x63, 0xe4, 0x3f, 0x47, 0xd8, 0xa9, 0xa8, 0x54, 0x16, 0xfb, 0xee, 0xbb,
	0xcf, 0xfe, 0x9d, 0x7d, 0xe8, 0x92, 0x19, 0x5d, 0xd3, 0xba, 0x29, 0xb9, 0x0c, 0xab, 0xae, 0xc2,
	0x4e, 0xb4, 0x51, 0x4e, 0xe1, 0xa1, 0x4f, 0xa6, 0x57, 0x4c, 0x29, 0xf6, 0x0a, 0xd4, 0x8b, 0x55,
	0xbb, 0xa5, 0x8e, 0x0b, 0xb0, 0xae, 0x14, 0x3a, 0xf8, 0x92, 0xef, 0x08, 0x0d, 0xf3, 0x5f, 0x2b,
	0x3e, 0x41, 0xbd, 0xe5, 0x26, 0x8e, 0x66, 0xd1, 0xfc, 0xb8, 0xe8, 0x2d, 0x37, 0x18, 0xa3, 0xc1,
	0x53, 0x29, 0x20, 0xee, 0x79, 0xc5, 0xc7, 0xf8, 0x16, 0x8d, 0x17, 0x20, 0xc1, 0x72, 0xbb, 0xe6,
	0x02, 0xe2, 0xfe, 0x2c, 0x9a, 0x8f, 0xb3, 0x29, 0x09, 0x10, 0xb2, 0x83, 0x90, 0xf5, 0x0e, 0x52,
	0xec, 0xdb, 0xf1, 0x39, 0x1a, 0x3d, 0x02, 0x67, 0x8d, 0x8b, 0x07, 0xb3, 0x68, 0xde, 0x2f, 0xba,
	0x2c, 0x39, 0x43, 0xa7, 0x0b, 0x70, 0x79, 0x6b, 0x0c, 0x48, 0x57, 0xc0, 0x5b, 0x0b, 0xd6, 0x25,
	0x37, 0x08, 0xef, 0x8b, 0x56, 0x2b, 0x69, 0x01, 0x27, 0x5d, 0xb7, 0xbe, 0xcf, 0x71, 0x36, 0x21,
	0xe1, 0xcd, 0x5e, 0x2b, 0x42, 0x29, 0x5b, 0xa1, 0x89, 0x0f, 0x56, 0x60, 0xde, 0x79, 0x0d, 0x38,
	0x47, 0xe8, 0xef, 0x26, 0x1c, 0x77, 0x47, 0x0e, 0x88, 0xd3, 0x8b, 0x7f, 0x2a, 0x01, 0x9b, 0x1c,
	0x3d, 0xdc, 0x3f, 0xdf, 0x31, 0xee, 0x9a, 0xb6, 0x22, 0xb5, 0x12, 0x74, 0xcb, 0x99, 0x00, 0xe9,
	0x52, 0x09, 0xee, 0x43, 0x99, 0x17, 0x4b, 0x55, 0x69, 0xb9, 0x4d, 0x8d, 0xae, 0x53, 0x6d, 0xd4,
	0xe7, 0x17, 0x3d, 0x9c, 0x4e, 0x35, 0xf2, 0xdf, 0x73, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xfb,
	0xe7, 0x96, 0x92, 0xba, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChainServiceClient is the client API for ChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChainServiceClient interface {
	GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*GetCurrentResponse, error)
}

type chainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChainServiceClient(cc grpc.ClientConnInterface) ChainServiceClient {
	return &chainServiceClient{cc}
}

func (c *chainServiceClient) GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*GetCurrentResponse, error) {
	out := new(GetCurrentResponse)
	err := c.cc.Invoke(ctx, "/chain.ChainService/GetCurrent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainServiceServer is the server API for ChainService service.
type ChainServiceServer interface {
	GetCurrent(context.Context, *GetCurrentRequest) (*GetCurrentResponse, error)
}

// UnimplementedChainServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChainServiceServer struct {
}

func (*UnimplementedChainServiceServer) GetCurrent(ctx context.Context, req *GetCurrentRequest) (*GetCurrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrent not implemented")
}

func RegisterChainServiceServer(s *grpc.Server, srv ChainServiceServer) {
	s.RegisterService(&_ChainService_serviceDesc, srv)
}

func _ChainService_GetCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainServiceServer).GetCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chain.ChainService/GetCurrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainServiceServer).GetCurrent(ctx, req.(*GetCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chain.ChainService",
	HandlerType: (*ChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrent",
			Handler:    _ChainService_GetCurrent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/chain/chainpb/chain.proto",
}
