// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/delegation/delegationpb/delegation.proto

package delegationpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DelegationEntry struct {
	Entries              map[string]*Delegation `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DelegationEntry) Reset()         { *m = DelegationEntry{} }
func (m *DelegationEntry) String() string { return proto.CompactTextString(m) }
func (*DelegationEntry) ProtoMessage()    {}
func (*DelegationEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8c295276666357, []int{0}
}

func (m *DelegationEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegationEntry.Unmarshal(m, b)
}
func (m *DelegationEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegationEntry.Marshal(b, m, deterministic)
}
func (m *DelegationEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationEntry.Merge(m, src)
}
func (m *DelegationEntry) XXX_Size() int {
	return xxx_messageInfo_DelegationEntry.Size(m)
}
func (m *DelegationEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationEntry proto.InternalMessageInfo

func (m *DelegationEntry) GetEntries() map[string]*Delegation {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Delegation struct {
	Shares               []byte   `protobuf:"bytes,1,opt,name=shares,proto3" json:"shares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delegation) Reset()         { *m = Delegation{} }
func (m *Delegation) String() string { return proto.CompactTextString(m) }
func (*Delegation) ProtoMessage()    {}
func (*Delegation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8c295276666357, []int{1}
}

func (m *Delegation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delegation.Unmarshal(m, b)
}
func (m *Delegation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delegation.Marshal(b, m, deterministic)
}
func (m *Delegation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delegation.Merge(m, src)
}
func (m *Delegation) XXX_Size() int {
	return xxx_messageInfo_Delegation.Size(m)
}
func (m *Delegation) XXX_DiscardUnknown() {
	xxx_messageInfo_Delegation.DiscardUnknown(m)
}

var xxx_messageInfo_Delegation proto.InternalMessageInfo

func (m *Delegation) GetShares() []byte {
	if m != nil {
		return m.Shares
	}
	return nil
}

type GetByPublicKeyRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByPublicKeyRequest) Reset()         { *m = GetByPublicKeyRequest{} }
func (m *GetByPublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetByPublicKeyRequest) ProtoMessage()    {}
func (*GetByPublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8c295276666357, []int{2}
}

func (m *GetByPublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPublicKeyRequest.Unmarshal(m, b)
}
func (m *GetByPublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetByPublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPublicKeyRequest.Merge(m, src)
}
func (m *GetByPublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetByPublicKeyRequest.Size(m)
}
func (m *GetByPublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPublicKeyRequest proto.InternalMessageInfo

func (m *GetByPublicKeyRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *GetByPublicKeyRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByPublicKeyResponse struct {
	Delegations          map[string]*Delegation `protobuf:"bytes,1,rep,name=delegations,proto3" json:"delegations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetByPublicKeyResponse) Reset()         { *m = GetByPublicKeyResponse{} }
func (m *GetByPublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetByPublicKeyResponse) ProtoMessage()    {}
func (*GetByPublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a8c295276666357, []int{3}
}

func (m *GetByPublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPublicKeyResponse.Unmarshal(m, b)
}
func (m *GetByPublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPublicKeyResponse.Marshal(b, m, deterministic)
}
func (m *GetByPublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPublicKeyResponse.Merge(m, src)
}
func (m *GetByPublicKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetByPublicKeyResponse.Size(m)
}
func (m *GetByPublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPublicKeyResponse proto.InternalMessageInfo

func (m *GetByPublicKeyResponse) GetDelegations() map[string]*Delegation {
	if m != nil {
		return m.Delegations
	}
	return nil
}

func init() {
	proto.RegisterType((*DelegationEntry)(nil), "delegation.DelegationEntry")
	proto.RegisterMapType((map[string]*Delegation)(nil), "delegation.DelegationEntry.EntriesEntry")
	proto.RegisterType((*Delegation)(nil), "delegation.Delegation")
	proto.RegisterType((*GetByPublicKeyRequest)(nil), "delegation.GetByPublicKeyRequest")
	proto.RegisterType((*GetByPublicKeyResponse)(nil), "delegation.GetByPublicKeyResponse")
	proto.RegisterMapType((map[string]*Delegation)(nil), "delegation.GetByPublicKeyResponse.DelegationsEntry")
}

func init() {
	proto.RegisterFile("grpc/delegation/delegationpb/delegation.proto", fileDescriptor_6a8c295276666357)
}

var fileDescriptor_6a8c295276666357 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x7d, 0xd3, 0xf2, 0xfa, 0xe8, 0x6d, 0x79, 0xd6, 0x01, 0x4b, 0x29, 0x08, 0x35, 0xb8, 0xc8,
	0xc2, 0x24, 0xd0, 0x6e, 0xc4, 0x65, 0xb1, 0x28, 0x0a, 0x22, 0x11, 0x05, 0xdd, 0x48, 0x12, 0xaf,
	0xc9, 0xd0, 0x36, 0x33, 0xce, 0x4c, 0xaa, 0xf9, 0x24, 0xbf, 0xc4, 0xdf, 0x92, 0xa6, 0xad, 0x19,
	0x4b, 0xa9, 0x1b, 0x77, 0x73, 0xe6, 0x9e, 0x39, 0x73, 0xce, 0xe1, 0x82, 0x13, 0x4b, 0x11, 0x79,
	0x4f, 0x38, 0xc1, 0x38, 0xd0, 0x8c, 0xa7, 0xc6, 0x51, 0x84, 0x06, 0x70, 0x85, 0xe4, 0x9a, 0x53,
	0x28, 0x6f, 0xac, 0x77, 0x02, 0x3b, 0xa7, 0x5f, 0x70, 0x94, 0x6a, 0x99, 0xd3, 0x21, 0xfc, 0xc3,
	0x54, 0x4b, 0x86, 0xaa, 0x43, 0x7a, 0x55, 0xbb, 0xd1, 0xb7, 0x5d, 0x43, 0x63, 0x8d, 0xed, 0x8e,
	0x16, 0xd4, 0x02, 0xf8, 0xab, 0x87, 0x5d, 0x1f, 0x9a, 0xe6, 0x80, 0xb6, 0xa0, 0x3a, 0xc6, 0xbc,
	0x43, 0x7a, 0xc4, 0xae, 0xfb, 0xf3, 0x23, 0x3d, 0x82, 0xbf, 0xb3, 0x60, 0x92, 0x61, 0xa7, 0xd2,
	0x23, 0x76, 0xa3, 0xdf, 0xde, 0xfc, 0x87, 0xbf, 0x20, 0x9d, 0x54, 0x8e, 0x89, 0x75, 0x08, 0x50,
	0x0e, 0x68, 0x1b, 0x6a, 0x2a, 0x09, 0x64, 0x61, 0x92, 0xd8, 0x4d, 0x7f, 0x89, 0xac, 0x2b, 0xd8,
	0x3b, 0x43, 0x3d, 0xcc, 0xaf, 0xb3, 0x70, 0xc2, 0xa2, 0x4b, 0xcc, 0x7d, 0x7c, 0xc9, 0x50, 0x69,
	0xba, 0x0f, 0x20, 0x8a, 0xbb, 0xc7, 0xd2, 0x49, 0x5d, 0xac, 0x58, 0x73, 0xbd, 0x04, 0x59, 0x9c,
	0xe8, 0xc2, 0x50, 0xd5, 0x5f, 0x22, 0xeb, 0x83, 0x40, 0x7b, 0x5d, 0x50, 0x09, 0x9e, 0x2a, 0xa4,
	0xb7, 0xd0, 0x28, 0x4d, 0xaf, 0xca, 0x1a, 0x98, 0x41, 0x36, 0x3f, 0x34, 0xf2, 0x2d, 0x7b, 0x33,
	0x75, 0xba, 0x77, 0xd0, 0x5a, 0x27, 0xfc, 0x46, 0x7f, 0xfd, 0x14, 0x76, 0xcb, 0xc1, 0x0d, 0xca,
	0x19, 0x8b, 0x90, 0xde, 0xc3, 0xff, 0xef, 0x26, 0xe9, 0xc1, 0xb6, 0x00, 0x45, 0x95, 0x5d, 0xeb,
	0xe7, 0x8c, 0xd6, 0x9f, 0xe1, 0xc5, 0xc3, 0x79, 0xcc, 0x74, 0x92, 0x85, 0x6e, 0xc4, 0xa7, 0xde,
	0x33, 0x8b, 0xa7, 0x98, 0x6a, 0x27, 0x45, 0xfd, 0xca, 0xe5, 0x58, 0x79, 0x3c, 0x50, 0x4c, 0x39,
	0x52, 0x44, 0x8e, 0x90, 0xfc, 0x2d, 0xf7, 0xb6, 0x2d, 0x71, 0x58, 0x2b, 0x56, 0x77, 0xf0, 0x19,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0x2b, 0xc8, 0xf0, 0xeb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DelegationServiceClient is the client API for DelegationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DelegationServiceClient interface {
	GetByPublicKey(ctx context.Context, in *GetByPublicKeyRequest, opts ...grpc.CallOption) (*GetByPublicKeyResponse, error)
}

type delegationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDelegationServiceClient(cc grpc.ClientConnInterface) DelegationServiceClient {
	return &delegationServiceClient{cc}
}

func (c *delegationServiceClient) GetByPublicKey(ctx context.Context, in *GetByPublicKeyRequest, opts ...grpc.CallOption) (*GetByPublicKeyResponse, error) {
	out := new(GetByPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/delegation.DelegationService/GetByPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelegationServiceServer is the server API for DelegationService service.
type DelegationServiceServer interface {
	GetByPublicKey(context.Context, *GetByPublicKeyRequest) (*GetByPublicKeyResponse, error)
}

// UnimplementedDelegationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDelegationServiceServer struct {
}

func (*UnimplementedDelegationServiceServer) GetByPublicKey(ctx context.Context, req *GetByPublicKeyRequest) (*GetByPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByPublicKey not implemented")
}

func RegisterDelegationServiceServer(s *grpc.Server, srv DelegationServiceServer) {
	s.RegisterService(&_DelegationService_serviceDesc, srv)
}

func _DelegationService_GetByPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelegationServiceServer).GetByPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delegation.DelegationService/GetByPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelegationServiceServer).GetByPublicKey(ctx, req.(*GetByPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DelegationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "delegation.DelegationService",
	HandlerType: (*DelegationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByPublicKey",
			Handler:    _DelegationService_GetByPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/delegation/delegationpb/delegation.proto",
}
