// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/account/accountpb/account.proto

package accountpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GeneralAccount struct {
	Balance              []byte   `protobuf:"bytes,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Nonce                uint64   `protobuf:"varint,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	TransfersNotBefore   uint64   `protobuf:"varint,3,opt,name=TransfersNotBefore,proto3" json:"TransfersNotBefore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralAccount) Reset()         { *m = GeneralAccount{} }
func (m *GeneralAccount) String() string { return proto.CompactTextString(m) }
func (*GeneralAccount) ProtoMessage()    {}
func (*GeneralAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{0}
}

func (m *GeneralAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralAccount.Unmarshal(m, b)
}
func (m *GeneralAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralAccount.Marshal(b, m, deterministic)
}
func (m *GeneralAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralAccount.Merge(m, src)
}
func (m *GeneralAccount) XXX_Size() int {
	return xxx_messageInfo_GeneralAccount.Size(m)
}
func (m *GeneralAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralAccount.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralAccount proto.InternalMessageInfo

func (m *GeneralAccount) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *GeneralAccount) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *GeneralAccount) GetTransfersNotBefore() uint64 {
	if m != nil {
		return m.TransfersNotBefore
	}
	return 0
}

type SharePool struct {
	Balance              []byte   `protobuf:"bytes,1,opt,name=Balance,proto3" json:"Balance,omitempty"`
	TotalShares          []byte   `protobuf:"bytes,2,opt,name=TotalShares,proto3" json:"TotalShares,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharePool) Reset()         { *m = SharePool{} }
func (m *SharePool) String() string { return proto.CompactTextString(m) }
func (*SharePool) ProtoMessage()    {}
func (*SharePool) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{1}
}

func (m *SharePool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharePool.Unmarshal(m, b)
}
func (m *SharePool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharePool.Marshal(b, m, deterministic)
}
func (m *SharePool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharePool.Merge(m, src)
}
func (m *SharePool) XXX_Size() int {
	return xxx_messageInfo_SharePool.Size(m)
}
func (m *SharePool) XXX_DiscardUnknown() {
	xxx_messageInfo_SharePool.DiscardUnknown(m)
}

var xxx_messageInfo_SharePool proto.InternalMessageInfo

func (m *SharePool) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *SharePool) GetTotalShares() []byte {
	if m != nil {
		return m.TotalShares
	}
	return nil
}

type CommissionRateStep struct {
	Start                uint64   `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Rate                 []byte   `protobuf:"bytes,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommissionRateStep) Reset()         { *m = CommissionRateStep{} }
func (m *CommissionRateStep) String() string { return proto.CompactTextString(m) }
func (*CommissionRateStep) ProtoMessage()    {}
func (*CommissionRateStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{2}
}

func (m *CommissionRateStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommissionRateStep.Unmarshal(m, b)
}
func (m *CommissionRateStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommissionRateStep.Marshal(b, m, deterministic)
}
func (m *CommissionRateStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommissionRateStep.Merge(m, src)
}
func (m *CommissionRateStep) XXX_Size() int {
	return xxx_messageInfo_CommissionRateStep.Size(m)
}
func (m *CommissionRateStep) XXX_DiscardUnknown() {
	xxx_messageInfo_CommissionRateStep.DiscardUnknown(m)
}

var xxx_messageInfo_CommissionRateStep proto.InternalMessageInfo

func (m *CommissionRateStep) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *CommissionRateStep) GetRate() []byte {
	if m != nil {
		return m.Rate
	}
	return nil
}

type CommissionRateBoundStep struct {
	Start                uint64   `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	RateMin              []byte   `protobuf:"bytes,2,opt,name=RateMin,proto3" json:"RateMin,omitempty"`
	RateMax              []byte   `protobuf:"bytes,3,opt,name=RateMax,proto3" json:"RateMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommissionRateBoundStep) Reset()         { *m = CommissionRateBoundStep{} }
func (m *CommissionRateBoundStep) String() string { return proto.CompactTextString(m) }
func (*CommissionRateBoundStep) ProtoMessage()    {}
func (*CommissionRateBoundStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{3}
}

func (m *CommissionRateBoundStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommissionRateBoundStep.Unmarshal(m, b)
}
func (m *CommissionRateBoundStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommissionRateBoundStep.Marshal(b, m, deterministic)
}
func (m *CommissionRateBoundStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommissionRateBoundStep.Merge(m, src)
}
func (m *CommissionRateBoundStep) XXX_Size() int {
	return xxx_messageInfo_CommissionRateBoundStep.Size(m)
}
func (m *CommissionRateBoundStep) XXX_DiscardUnknown() {
	xxx_messageInfo_CommissionRateBoundStep.DiscardUnknown(m)
}

var xxx_messageInfo_CommissionRateBoundStep proto.InternalMessageInfo

func (m *CommissionRateBoundStep) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *CommissionRateBoundStep) GetRateMin() []byte {
	if m != nil {
		return m.RateMin
	}
	return nil
}

func (m *CommissionRateBoundStep) GetRateMax() []byte {
	if m != nil {
		return m.RateMax
	}
	return nil
}

type CommissionSchedule struct {
	Rates                []*CommissionRateStep      `protobuf:"bytes,1,rep,name=Rates,proto3" json:"Rates,omitempty"`
	Bounds               []*CommissionRateBoundStep `protobuf:"bytes,2,rep,name=Bounds,proto3" json:"Bounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CommissionSchedule) Reset()         { *m = CommissionSchedule{} }
func (m *CommissionSchedule) String() string { return proto.CompactTextString(m) }
func (*CommissionSchedule) ProtoMessage()    {}
func (*CommissionSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{4}
}

func (m *CommissionSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommissionSchedule.Unmarshal(m, b)
}
func (m *CommissionSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommissionSchedule.Marshal(b, m, deterministic)
}
func (m *CommissionSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommissionSchedule.Merge(m, src)
}
func (m *CommissionSchedule) XXX_Size() int {
	return xxx_messageInfo_CommissionSchedule.Size(m)
}
func (m *CommissionSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_CommissionSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_CommissionSchedule proto.InternalMessageInfo

func (m *CommissionSchedule) GetRates() []*CommissionRateStep {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *CommissionSchedule) GetBounds() []*CommissionRateBoundStep {
	if m != nil {
		return m.Bounds
	}
	return nil
}

// ThresholdKind is the kind of staking threshold.
type ThresholdKinds struct {
	Kinds                []int32  `protobuf:"varint,1,rep,packed,name=Kinds,proto3" json:"Kinds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThresholdKinds) Reset()         { *m = ThresholdKinds{} }
func (m *ThresholdKinds) String() string { return proto.CompactTextString(m) }
func (*ThresholdKinds) ProtoMessage()    {}
func (*ThresholdKinds) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{5}
}

func (m *ThresholdKinds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThresholdKinds.Unmarshal(m, b)
}
func (m *ThresholdKinds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThresholdKinds.Marshal(b, m, deterministic)
}
func (m *ThresholdKinds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThresholdKinds.Merge(m, src)
}
func (m *ThresholdKinds) XXX_Size() int {
	return xxx_messageInfo_ThresholdKinds.Size(m)
}
func (m *ThresholdKinds) XXX_DiscardUnknown() {
	xxx_messageInfo_ThresholdKinds.DiscardUnknown(m)
}

var xxx_messageInfo_ThresholdKinds proto.InternalMessageInfo

func (m *ThresholdKinds) GetKinds() []int32 {
	if m != nil {
		return m.Kinds
	}
	return nil
}

type StakeAccumulator struct {
	// Claims are the stake claims that must be satisfied at any given point. Adding a new claim is
	// only possible if all of the existing claims plus the new claim is satisfied.
	Claims               map[string]*ThresholdKinds `protobuf:"bytes,1,rep,name=Claims,proto3" json:"Claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StakeAccumulator) Reset()         { *m = StakeAccumulator{} }
func (m *StakeAccumulator) String() string { return proto.CompactTextString(m) }
func (*StakeAccumulator) ProtoMessage()    {}
func (*StakeAccumulator) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{6}
}

func (m *StakeAccumulator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeAccumulator.Unmarshal(m, b)
}
func (m *StakeAccumulator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeAccumulator.Marshal(b, m, deterministic)
}
func (m *StakeAccumulator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeAccumulator.Merge(m, src)
}
func (m *StakeAccumulator) XXX_Size() int {
	return xxx_messageInfo_StakeAccumulator.Size(m)
}
func (m *StakeAccumulator) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeAccumulator.DiscardUnknown(m)
}

var xxx_messageInfo_StakeAccumulator proto.InternalMessageInfo

func (m *StakeAccumulator) GetClaims() map[string]*ThresholdKinds {
	if m != nil {
		return m.Claims
	}
	return nil
}

type EscrowAccount struct {
	Active               *SharePool          `protobuf:"bytes,1,opt,name=Active,proto3" json:"Active,omitempty"`
	Debonding            *SharePool          `protobuf:"bytes,2,opt,name=Debonding,proto3" json:"Debonding,omitempty"`
	CommissionSchedule   *CommissionSchedule `protobuf:"bytes,3,opt,name=CommissionSchedule,proto3" json:"CommissionSchedule,omitempty"`
	StakeAccumulator     *StakeAccumulator   `protobuf:"bytes,4,opt,name=StakeAccumulator,proto3" json:"StakeAccumulator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EscrowAccount) Reset()         { *m = EscrowAccount{} }
func (m *EscrowAccount) String() string { return proto.CompactTextString(m) }
func (*EscrowAccount) ProtoMessage()    {}
func (*EscrowAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{7}
}

func (m *EscrowAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EscrowAccount.Unmarshal(m, b)
}
func (m *EscrowAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EscrowAccount.Marshal(b, m, deterministic)
}
func (m *EscrowAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EscrowAccount.Merge(m, src)
}
func (m *EscrowAccount) XXX_Size() int {
	return xxx_messageInfo_EscrowAccount.Size(m)
}
func (m *EscrowAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EscrowAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EscrowAccount proto.InternalMessageInfo

func (m *EscrowAccount) GetActive() *SharePool {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *EscrowAccount) GetDebonding() *SharePool {
	if m != nil {
		return m.Debonding
	}
	return nil
}

func (m *EscrowAccount) GetCommissionSchedule() *CommissionSchedule {
	if m != nil {
		return m.CommissionSchedule
	}
	return nil
}

func (m *EscrowAccount) GetStakeAccumulator() *StakeAccumulator {
	if m != nil {
		return m.StakeAccumulator
	}
	return nil
}

type Account struct {
	General              *GeneralAccount `protobuf:"bytes,1,opt,name=General,proto3" json:"General,omitempty"`
	Escrow               *EscrowAccount  `protobuf:"bytes,2,opt,name=Escrow,proto3" json:"Escrow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{8}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetGeneral() *GeneralAccount {
	if m != nil {
		return m.General
	}
	return nil
}

func (m *Account) GetEscrow() *EscrowAccount {
	if m != nil {
		return m.Escrow
	}
	return nil
}

type GetByPublicKeyRequest struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByPublicKeyRequest) Reset()         { *m = GetByPublicKeyRequest{} }
func (m *GetByPublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*GetByPublicKeyRequest) ProtoMessage()    {}
func (*GetByPublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{9}
}

func (m *GetByPublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPublicKeyRequest.Unmarshal(m, b)
}
func (m *GetByPublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *GetByPublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPublicKeyRequest.Merge(m, src)
}
func (m *GetByPublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_GetByPublicKeyRequest.Size(m)
}
func (m *GetByPublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPublicKeyRequest proto.InternalMessageInfo

func (m *GetByPublicKeyRequest) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *GetByPublicKeyRequest) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetByPublicKeyResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByPublicKeyResponse) Reset()         { *m = GetByPublicKeyResponse{} }
func (m *GetByPublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*GetByPublicKeyResponse) ProtoMessage()    {}
func (*GetByPublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b4bc31470b810eb, []int{10}
}

func (m *GetByPublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByPublicKeyResponse.Unmarshal(m, b)
}
func (m *GetByPublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByPublicKeyResponse.Marshal(b, m, deterministic)
}
func (m *GetByPublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByPublicKeyResponse.Merge(m, src)
}
func (m *GetByPublicKeyResponse) XXX_Size() int {
	return xxx_messageInfo_GetByPublicKeyResponse.Size(m)
}
func (m *GetByPublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByPublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByPublicKeyResponse proto.InternalMessageInfo

func (m *GetByPublicKeyResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*GeneralAccount)(nil), "account.GeneralAccount")
	proto.RegisterType((*SharePool)(nil), "account.SharePool")
	proto.RegisterType((*CommissionRateStep)(nil), "account.CommissionRateStep")
	proto.RegisterType((*CommissionRateBoundStep)(nil), "account.CommissionRateBoundStep")
	proto.RegisterType((*CommissionSchedule)(nil), "account.CommissionSchedule")
	proto.RegisterType((*ThresholdKinds)(nil), "account.ThresholdKinds")
	proto.RegisterType((*StakeAccumulator)(nil), "account.StakeAccumulator")
	proto.RegisterMapType((map[string]*ThresholdKinds)(nil), "account.StakeAccumulator.ClaimsEntry")
	proto.RegisterType((*EscrowAccount)(nil), "account.EscrowAccount")
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*GetByPublicKeyRequest)(nil), "account.GetByPublicKeyRequest")
	proto.RegisterType((*GetByPublicKeyResponse)(nil), "account.GetByPublicKeyResponse")
}

func init() {
	proto.RegisterFile("grpc/account/accountpb/account.proto", fileDescriptor_3b4bc31470b810eb)
}

var fileDescriptor_3b4bc31470b810eb = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdf, 0x4f, 0xdb, 0x30,
	0x10, 0x5e, 0xe8, 0x2f, 0xf5, 0xca, 0x10, 0xb2, 0xb6, 0x92, 0x31, 0x6d, 0xab, 0xa2, 0x6d, 0x42,
	0x48, 0xeb, 0x46, 0xf7, 0x82, 0x26, 0x6d, 0x12, 0x05, 0xc4, 0x03, 0x1a, 0x42, 0x0e, 0x4f, 0x7b,
	0x99, 0xdc, 0xf4, 0x20, 0x11, 0xa9, 0x9d, 0xd9, 0x0e, 0xa3, 0x8f, 0xfc, 0x31, 0xfb, 0x3f, 0xa7,
	0x38, 0x76, 0xda, 0x42, 0xe0, 0x29, 0xbe, 0xf3, 0x77, 0x3f, 0xbe, 0xef, 0x9c, 0x83, 0xf7, 0x57,
	0x32, 0x8b, 0x3e, 0xb3, 0x28, 0x12, 0x39, 0xd7, 0xee, 0x9b, 0x4d, 0xdc, 0x69, 0x98, 0x49, 0xa1,
	0x05, 0xe9, 0x58, 0x33, 0xc8, 0x60, 0xe3, 0x04, 0x39, 0x4a, 0x96, 0x1e, 0x94, 0x1e, 0xe2, 0x43,
	0x67, 0xcc, 0x52, 0xc6, 0x23, 0xf4, 0xbd, 0x81, 0xb7, 0xb3, 0x4e, 0x9d, 0x49, 0x5e, 0x40, 0xeb,
	0x4c, 0x14, 0xfe, 0xb5, 0x81, 0xb7, 0xd3, 0xa4, 0xa5, 0x41, 0x86, 0x40, 0x2e, 0x24, 0xe3, 0xea,
	0x12, 0xa5, 0x3a, 0x13, 0x7a, 0x8c, 0x97, 0x42, 0xa2, 0xdf, 0x30, 0x90, 0x9a, 0x9b, 0xe0, 0x04,
	0xba, 0x61, 0xcc, 0x24, 0x9e, 0x0b, 0x91, 0x3e, 0x51, 0x6c, 0x00, 0xbd, 0x0b, 0xa1, 0x59, 0x6a,
	0xb0, 0xca, 0x94, 0x5c, 0xa7, 0xcb, 0xae, 0xe0, 0x07, 0x90, 0x43, 0x31, 0x9b, 0x25, 0x4a, 0x25,
	0x82, 0x53, 0xa6, 0x31, 0xd4, 0x98, 0x15, 0x4d, 0x86, 0x9a, 0x49, 0x6d, 0xf2, 0x35, 0x69, 0x69,
	0x10, 0x02, 0xcd, 0x02, 0x61, 0xd3, 0x98, 0x73, 0x10, 0xc1, 0xd6, 0x6a, 0xfc, 0x58, 0xe4, 0x7c,
	0xfa, 0x44, 0x12, 0x1f, 0x3a, 0x05, 0xec, 0x67, 0xc2, 0x6d, 0x1e, 0x67, 0x56, 0x37, 0xec, 0xd6,
	0x10, 0x77, 0x37, 0xec, 0x36, 0xb8, 0xf3, 0x96, 0xbb, 0x0c, 0xa3, 0x18, 0xa7, 0x79, 0x8a, 0x64,
	0x0f, 0x5a, 0x05, 0x42, 0xf9, 0xde, 0xa0, 0xb1, 0xd3, 0x1b, 0xbd, 0x1e, 0xba, 0xf1, 0x3c, 0x64,
	0x44, 0x4b, 0x24, 0xd9, 0x87, 0xb6, 0x69, 0xb0, 0xd0, 0xa2, 0x88, 0x19, 0x3c, 0x12, 0x53, 0xb1,
	0xa0, 0x16, 0x1f, 0x7c, 0x84, 0x8d, 0x8b, 0x58, 0xa2, 0x8a, 0x45, 0x3a, 0x3d, 0x4d, 0xf8, 0x54,
	0x15, 0xfc, 0xcc, 0xc1, 0x94, 0x6f, 0xd1, 0xd2, 0x08, 0xfe, 0x79, 0xb0, 0x19, 0x6a, 0x76, 0x8d,
	0x07, 0x51, 0x94, 0xcf, 0xf2, 0x94, 0x69, 0x21, 0xc9, 0x77, 0x68, 0x1f, 0xa6, 0x2c, 0x99, 0xb9,
	0x56, 0x3f, 0x54, 0x65, 0xef, 0x43, 0x87, 0x25, 0xee, 0x98, 0x6b, 0x39, 0xa7, 0x36, 0x68, 0x9b,
	0x42, 0x6f, 0xc9, 0x4d, 0x36, 0xa1, 0x71, 0x8d, 0x73, 0x23, 0x6b, 0x97, 0x16, 0x47, 0xf2, 0x09,
	0x5a, 0x37, 0x2c, 0xcd, 0xcb, 0xd1, 0xf4, 0x46, 0x5b, 0x55, 0xfa, 0xd5, 0x96, 0x69, 0x89, 0xfa,
	0xb6, 0xb6, 0xef, 0x05, 0x77, 0x6b, 0xf0, 0xfc, 0x58, 0x45, 0x52, 0xfc, 0x75, 0x6f, 0x76, 0x17,
	0xda, 0x07, 0x91, 0x4e, 0x6e, 0xca, 0x57, 0xd4, 0x1b, 0x91, 0x45, 0x93, 0xee, 0xa9, 0x51, 0x8b,
	0x20, 0x5f, 0xa0, 0x7b, 0x84, 0x13, 0xc1, 0xa7, 0x09, 0xbf, 0xb2, 0x45, 0xeb, 0xe0, 0x0b, 0x10,
	0x39, 0xad, 0x1b, 0xa1, 0x19, 0x74, 0xfd, 0xe4, 0x1c, 0x84, 0xd6, 0x4d, 0xfe, 0xf8, 0xa1, 0xc6,
	0x7e, 0xd3, 0xa4, 0x7a, 0xf5, 0xa8, 0xb2, 0xf4, 0x41, 0x48, 0x90, 0x42, 0xc7, 0x91, 0xdf, 0x83,
	0x8e, 0xfd, 0x85, 0x2d, 0xfb, 0x85, 0x86, 0xab, 0xbf, 0x36, 0x75, 0x38, 0x32, 0x84, 0x76, 0x29,
	0xa0, 0x15, 0xa0, 0x5f, 0x45, 0xac, 0xe8, 0x4a, 0x2d, 0x2a, 0x38, 0x83, 0x97, 0x27, 0xa8, 0xc7,
	0xf3, 0xf3, 0x7c, 0x92, 0x26, 0xd1, 0x29, 0xce, 0x29, 0xfe, 0xc9, 0x51, 0x69, 0xf2, 0x06, 0x20,
	0x33, 0xbe, 0xdf, 0x8b, 0xb1, 0x76, 0x33, 0x87, 0x22, 0x7d, 0x68, 0xc7, 0x98, 0x5c, 0xc5, 0xda,
	0xd4, 0x69, 0x50, 0x6b, 0x05, 0x47, 0xd0, 0xbf, 0x9f, 0x4f, 0x65, 0x82, 0x2b, 0x24, 0xbb, 0xe0,
	0x56, 0x93, 0x25, 0xb3, 0x59, 0xb5, 0x56, 0xb1, 0xb0, 0x8e, 0x11, 0xc2, 0x86, 0xf5, 0x85, 0x28,
	0x6f, 0x92, 0x08, 0x49, 0x58, 0x6c, 0xb3, 0xe5, 0xbc, 0xe4, 0xed, 0x92, 0x16, 0x35, 0x04, 0xb6,
	0xdf, 0x3d, 0x7a, 0x5f, 0x36, 0x14, 0x3c, 0x1b, 0xfb, 0xbf, 0xfa, 0xf5, 0x3b, 0x75, 0xd2, 0x36,
	0xcb, 0xf4, 0xeb, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x89, 0xb2, 0x53, 0x74, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	GetByPublicKey(ctx context.Context, in *GetByPublicKeyRequest, opts ...grpc.CallOption) (*GetByPublicKeyResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetByPublicKey(ctx context.Context, in *GetByPublicKeyRequest, opts ...grpc.CallOption) (*GetByPublicKeyResponse, error) {
	out := new(GetByPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetByPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	GetByPublicKey(context.Context, *GetByPublicKeyRequest) (*GetByPublicKeyResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) GetByPublicKey(ctx context.Context, req *GetByPublicKeyRequest) (*GetByPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByPublicKey not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetByPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetByPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByPublicKey(ctx, req.(*GetByPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByPublicKey",
			Handler:    _AccountService_GetByPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/account/accountpb/account.proto",
}
