// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: grpc/event/eventpb/event.proto

package eventpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetAddEscrowEventsByHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetAddEscrowEventsByHeightRequest) Reset() {
	*x = GetAddEscrowEventsByHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_event_eventpb_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddEscrowEventsByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddEscrowEventsByHeightRequest) ProtoMessage() {}

func (x *GetAddEscrowEventsByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_event_eventpb_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddEscrowEventsByHeightRequest.ProtoReflect.Descriptor instead.
func (*GetAddEscrowEventsByHeightRequest) Descriptor() ([]byte, []int) {
	return file_grpc_event_eventpb_event_proto_rawDescGZIP(), []int{0}
}

func (x *GetAddEscrowEventsByHeightRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type AddEscrowEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner  string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Escrow string `protobuf:"bytes,2,opt,name=escrow,proto3" json:"escrow,omitempty"`
	Amount []byte `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AddEscrowEvent) Reset() {
	*x = AddEscrowEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_event_eventpb_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEscrowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEscrowEvent) ProtoMessage() {}

func (x *AddEscrowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_event_eventpb_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEscrowEvent.ProtoReflect.Descriptor instead.
func (*AddEscrowEvent) Descriptor() ([]byte, []int) {
	return file_grpc_event_eventpb_event_proto_rawDescGZIP(), []int{1}
}

func (x *AddEscrowEvent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AddEscrowEvent) GetEscrow() string {
	if x != nil {
		return x.Escrow
	}
	return ""
}

func (x *AddEscrowEvent) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

type GetAddEscrowEventsByHeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*AddEscrowEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *GetAddEscrowEventsByHeightResponse) Reset() {
	*x = GetAddEscrowEventsByHeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_event_eventpb_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAddEscrowEventsByHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddEscrowEventsByHeightResponse) ProtoMessage() {}

func (x *GetAddEscrowEventsByHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_event_eventpb_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddEscrowEventsByHeightResponse.ProtoReflect.Descriptor instead.
func (*GetAddEscrowEventsByHeightResponse) Descriptor() ([]byte, []int) {
	return file_grpc_event_eventpb_event_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddEscrowEventsByHeightResponse) GetEvents() []*AddEscrowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_grpc_event_eventpb_event_proto protoreflect.FileDescriptor

var file_grpc_event_eventpb_event_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x70, 0x62, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x22, 0x56, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x45, 0x73, 0x63, 0x72, 0x6f,
	0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x73,
	0x63, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x22,
	0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x73,
	0x63, 0x72, 0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0x83, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x73, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x45, 0x73, 0x63, 0x72,
	0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x28, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x45,
	0x73, 0x63, 0x72, 0x6f, 0x77, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x45, 0x73, 0x63, 0x72, 0x6f, 0x77, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x6f, 0x61, 0x73, 0x69, 0x73, 0x2d, 0x72, 0x70, 0x63,
	0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_grpc_event_eventpb_event_proto_rawDescOnce sync.Once
	file_grpc_event_eventpb_event_proto_rawDescData = file_grpc_event_eventpb_event_proto_rawDesc
)

func file_grpc_event_eventpb_event_proto_rawDescGZIP() []byte {
	file_grpc_event_eventpb_event_proto_rawDescOnce.Do(func() {
		file_grpc_event_eventpb_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_event_eventpb_event_proto_rawDescData)
	})
	return file_grpc_event_eventpb_event_proto_rawDescData
}

var file_grpc_event_eventpb_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_event_eventpb_event_proto_goTypes = []interface{}{
	(*GetAddEscrowEventsByHeightRequest)(nil),  // 0: event.GetAddEscrowEventsByHeightRequest
	(*AddEscrowEvent)(nil),                     // 1: event.AddEscrowEvent
	(*GetAddEscrowEventsByHeightResponse)(nil), // 2: event.GetAddEscrowEventsByHeightResponse
}
var file_grpc_event_eventpb_event_proto_depIdxs = []int32{
	1, // 0: event.GetAddEscrowEventsByHeightResponse.events:type_name -> event.AddEscrowEvent
	0, // 1: event.EventService.GetAddEscrowEventsByHeight:input_type -> event.GetAddEscrowEventsByHeightRequest
	2, // 2: event.EventService.GetAddEscrowEventsByHeight:output_type -> event.GetAddEscrowEventsByHeightResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_event_eventpb_event_proto_init() }
func file_grpc_event_eventpb_event_proto_init() {
	if File_grpc_event_eventpb_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_event_eventpb_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddEscrowEventsByHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_event_eventpb_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEscrowEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_event_eventpb_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAddEscrowEventsByHeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_event_eventpb_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_event_eventpb_event_proto_goTypes,
		DependencyIndexes: file_grpc_event_eventpb_event_proto_depIdxs,
		MessageInfos:      file_grpc_event_eventpb_event_proto_msgTypes,
	}.Build()
	File_grpc_event_eventpb_event_proto = out.File
	file_grpc_event_eventpb_event_proto_rawDesc = nil
	file_grpc_event_eventpb_event_proto_goTypes = nil
	file_grpc_event_eventpb_event_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	GetAddEscrowEventsByHeight(ctx context.Context, in *GetAddEscrowEventsByHeightRequest, opts ...grpc.CallOption) (*GetAddEscrowEventsByHeightResponse, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) GetAddEscrowEventsByHeight(ctx context.Context, in *GetAddEscrowEventsByHeightRequest, opts ...grpc.CallOption) (*GetAddEscrowEventsByHeightResponse, error) {
	out := new(GetAddEscrowEventsByHeightResponse)
	err := c.cc.Invoke(ctx, "/event.EventService/GetAddEscrowEventsByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	GetAddEscrowEventsByHeight(context.Context, *GetAddEscrowEventsByHeightRequest) (*GetAddEscrowEventsByHeightResponse, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) GetAddEscrowEventsByHeight(context.Context, *GetAddEscrowEventsByHeightRequest) (*GetAddEscrowEventsByHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddEscrowEventsByHeight not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_GetAddEscrowEventsByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddEscrowEventsByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetAddEscrowEventsByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/GetAddEscrowEventsByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetAddEscrowEventsByHeight(ctx, req.(*GetAddEscrowEventsByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddEscrowEventsByHeight",
			Handler:    _EventService_GetAddEscrowEventsByHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/event/eventpb/event.proto",
}
